### ISSUE TITLE
Add link to devpost on project card

### ISSUE THREAD

**Issue by mjrb** [HackRU/sledge#139]
right now we import the names of projects and table numbers from dev post and i think the summaries too, however for the online hackathon we may need a few extra things since the judges wont be in person. We definitely need to also add a link to see the project on devpost, since the hackers will be required to also put a demo video on devpost for judges to watch.

Other things may be interesting to add but this is the main thing I'm looking for.

**Comment by samuel-ping** [comment]
@mjrb 

So I added links to devpost for each project cards on the judging screen. It definitely works, but I'm looking at the unit tests that it failed. I've gotten that error before in the unit test, but I have no idea how to start fixing it.

Here's my [branch](https://github.com/HackRU/sledge/tree/add_devpost_link_to_project_cards)

**Comment by mjrb** [comment]
Here is the build log in github actions [link](https://github.com/HackRU/sledge/runs/1285407687?check_suite_focus=true) it seems like you added a url feild to the database but the tests aren't aware of that. It might be inserting test data that doesn't have a url which causes a fail. Check the long and look in that test file to see
