### ISSUE TITLE
slack table channel creation scripts

### ISSUE THREAD

**Issue by mjrb** [HackRU/sledge#140]
since we have an online event, judges wont be able to walk up to tables and ask people questions. in lieu of that, we're going to have table channels in slack where judges can ask a hackers questions, which will correspond to the table number assigned in devpost.

we need some one to create a script that uses the slack api and creates N slack channels named "judging table n". you can test it out by using your own test slack workspace [slack documentation](https://api.slack.com/methods/channels.create)

**Comment by samuel-ping** [comment]
[channels is deprecated, replace with conversations](https://api.slack.com/methods/conversations.create)?

**Comment by samuel-ping** [comment]
nvm slack bots still using channels.create

**Comment by samuel-ping** [comment]
A server needs to be hosted for slack bot:
1. Should we use the current server
2. If so, I should handle requests using TypeScript + Express, I think?

**Comment by mjrb** [comment]
Is there any way were we can do this with a script, and it logs in as a user through oauth instead of needing to create a bot

**Comment by samuel-ping** [comment]
okay, I do think this can be written with a Python script [using this to guide me](https://github.com/slackapi/python-slackclient#slackclient-as-a-script), unless it is preferable to write it in a different programming language?

**Comment by sahej172002** [comment]
Sam I think most of our scripts are written in typescript if im not mistaken. Not sure how much work it is to change the python script to TS tho

**Comment by samuel-ping** [comment]
@mjrb 
### Update 2:
I created a working mvp :) You were right Mickey, I was able to use an OAuth token. I only realized that after I used it. Here you go: [working mvp](https://github.com/samuel-ping/slack-judge-table-creator)

Should I add my script to a branch on this Sledge repo and open a pull request? If so, do I make a scripts/ directory in root?

### Update
Okay so I think I can make this script.... I ran a post request through postman and it successfully created a channel! Magical!

### Original
Okay, I'm fairly sure it can't be done with a script, the best thing you can do in a script is to use a webhook to [send messages to a channel](https://api.slack.com/messaging/webhooks) (I think). 

To create channels in Slack, you have to use the conversations.create() function. To me, it seems like the best way (and easiest way for me... I think?) is to use [this code snippet](https://api.slack.com/methods/conversations.create/code) to help guide me.

Possible problems with the approach I mentioned:
1. not sure what the best way/how to trigger the script
2. need to host it on a server somewhere
3. I feel like there's other issues with this I'm not seeing lol

I think I can also try going back to using a slash command with a bot to achieve this, and the slash command can be restricted to a channel.

Hold up... reading [this](https://api.slack.com/web#posting_json) rn...

**Comment by mjrb** [comment]
Awesome this looks pretty good, but could you open a or on this repo to add your code to the tools folder. For future reference you should open prs for stuff instead of creating new repos.

After you do a pr we have an opportunity to do code review on the stuff you add to help you learn best practices, write cleaner code, and discuss any issues

**Comment by samuel-ping** [comment]
okay great! Yeah my bad, I wasn't sure where I would put the script and I wanted to put the script somewhere lol so I made a new repo.
