### ISSUE TITLE
add/audit automated testing and CI

### ISSUE THREAD

**Issue by mjrb** [HackRU/sledge#141]
add back some tests with a testing framework like jest and add in travis ci to make sure people can't commit buggy code on pull requests.

also eric I may be confused, so please be gentle.

**Comment by shivanmodha** [comment]
@samuel-ping seems like we have github-actions integration already, lets see if we can just update it to catch potential errors during the code review process.

**Comment by samuel-ping** [comment]
Notes to self:
- Look at [this](https://github.com/mtiller/ts-jest-sample) for reference and code coverage
- Look into branch-specific badges ([branch parameter in url](https://github.community/t/workflow-status-badge-per-branch/16198/6?u=samuel-ping), [example](https://stackoverflow.com/a/35368808/13026376))
- [snapshot testing?](https://jestjs.io/docs/en/snapshot-testing)

**Comment by samuel-ping** [comment]
Migrated to ts-jest for [type checking](https://kulshekhar.github.io/ts-jest/docs/babel7-or-ts#no-type-checking) in 294db55fb39fcaa1eec4f81c93b8d1b46f9e16ce
