### ISSUE TITLE
Submission table schema

### ISSUE THREAD

**Issue by sahej172002** [HackRU/sledge#157]
Create database (table) schema for submissions by teams based on pre-written requirements.
https://docs.google.com/document/d/1LHPRmeCmtM1XnATNZywi5Q_VqADvGyvJ0ihpS8KUNbA/edit#

**Comment by samuel-ping** [comment]
Hm what's the best way for a SQL table to look from nested JSON? I don't want to do [this](https://d2908q01vomqb2.cloudfront.net/b6692ea5df920cad691c20319a6fffd7a4a766b8/2019/01/16/AthenaJSON8.png)...

**Comment by sahej172002** [comment]
In our case, what would be the parent and children?

**Comment by samuel-ping** [comment]
Fixed in 73c24568c4188949590467fec1c4a4cb6ffa897f
