### ISSUE TITLE
Add login functionality

### ISSUE THREAD

**Issue by three** [HackRU/sledge#3]
We need a way for judges to login and prove that they are judges. The plan is to have a login page where judges can select who they are and enter a numeric code (like TOTP) given to them by an admin. If they enter the correct code they receive a secret token (stored in localstorage) which will be used by judge.html to log them in.

**Comment by three** [comment]
cc @Kironb

**Comment by Kironb** [comment]
So far I have a sort of general login page working (where they could enter a user and password, have it be verified/sent to another page). How exactly should I have it connect it to judge html?

**Comment by three** [comment]
@Kironb Push what you have into a branch so I can take a look at it.
